apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: argo-hub
servers: 1
agents: 0
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 6443:6443
    nodeFilters:
      - server:0
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
    disableImageVolume: false
network: argocd-net
