apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: argo-managed
servers: 1
agents: 0
ports:
  - port: 6444:6443
    nodeFilters:
      - server:0
options:
  k3d:
    wait: true
    timeout: "60s"
network: argocd-net
