apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nginx-demo-project
  namespace: argocd
spec:
  description: "Project for Nginx Demo Application"
  # Allow manifests to be pulled from any repo (or restrict to yours)
  sourceRepos:
  - '*'
  # Only allow deploying to the managed cluster in the guestbook namespaces
  destinations:
  - namespace: nginx-demo
    server: https://k3d-argo-managed-serverlb:6443
  - namespace: nginx-demo-dev
    server: https://k3d-argo-managed-serverlb:6443
  # Allow creating Namespaces (since we use CreateNamespace=true)
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
